# Generated by Django 5.0 on 2023-12-09 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_Name', models.CharField(max_length=40)),
                ('Aadhar_Number', models.IntegerField()),
                ('Address', models.TextField(max_length=200)),
                ('Joined_Date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(default=None, max_length=100)),
                ('Contact_Number', models.IntegerField(blank=True, null=True)),
                ('Vehicle_Number', models.CharField(max_length=15)),
                ('Vin_Number', models.CharField(max_length=30)),
                ('Wash_In_Timings', models.DateTimeField(blank=True, null=True)),
                ('Wash_Out_Timings', models.DateTimeField(blank=True, null=True)),
                ('Delivery_Time', models.DateTimeField(blank=True, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Service_Cost', models.IntegerField(blank=True, null=True)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleDetails.workerdetail')),
            ],
        ),
    ]
