# Generated by Django 4.2.8 on 2023-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(default=None, max_length=100)),
                ('ContactNumber', models.IntegerField(max_length=15)),
                ('VehicleNumber', models.CharField(max_length=15)),
                ('VinNumber', models.CharField(max_length=30)),
                ('WashInTimings', models.DateTimeField()),
                ('WashOutTimings', models.DateTimeField()),
                ('DeliveryTime', models.DateTimeField()),
            ],
        ),
    ]
