# Generated by Django 5.0 on 2023-12-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='Worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicleDetails.workerdetail'),
        ),
    ]
