# Generated by Django 4.2.8 on 2023-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='DeliveryTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='WashInTimings',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='WashOutTimings',
            field=models.DateTimeField(null=True),
        ),
    ]
