# Generated by Django 5.0 on 2023-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleDetails", "0002_alter_vehicledetail_worker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Worker",
        ),
        migrations.RenameField(
            model_name="vehicledetail",
            old_name="Vin_Number",
            new_name="Model",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Contact_Number",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Customer_Name",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Delivery_Time",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Remarks",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Service_Cost",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Wash_In_Timings",
        ),
        migrations.RemoveField(
            model_name="vehicledetail",
            name="Wash_Out_Timings",
        ),
        migrations.AddField(
            model_name="vehicledetail",
            name="Date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="Vehicle_Number",
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name="WorkerDetail",
        ),
    ]
