# Generated by Django 4.2.8 on 2023-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0002_alter_vehicledetails_deliverytime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(default=None, max_length=100)),
                ('ContactNumber', models.IntegerField(max_length=15)),
                ('VehicleNumber', models.CharField(max_length=15)),
                ('VinNumber', models.CharField(max_length=30)),
                ('WashInTimings', models.DateTimeField(blank=True)),
                ('WashOutTimings', models.DateTimeField(blank=True)),
                ('DeliveryTime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleDetails',
        ),
    ]
