# Generated by Django 5.0 on 2023-12-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleDetails", "0003_remove_vehicledetail_worker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledetail",
            name="Vehicle_Number",
            field=models.TextField(max_length=40),
        ),
    ]
