# Generated by Django 4.2.8 on 2023-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0003_vehicledetail_delete_vehicledetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='DeliveryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='WashInTimings',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='WashOutTimings',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
