# Generated by Django 5.0 on 2023-12-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleDetails", "0004_alter_vehicledetail_vehicle_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledetail",
            name="Date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vehicledetail",
            name="Vehicle_Number",
            field=models.CharField(max_length=40),
        ),
    ]
