# Generated by Django 4.2.8 on 2023-12-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0004_alter_vehicledetail_deliverytime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='ContactNumber',
            new_name='Contact_Number',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='CustomerName',
            new_name='Customer_Name',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='DeliveryTime',
            new_name='Delivery_Time',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='VehicleNumber',
            new_name='Vehicle_Number',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='VinNumber',
            new_name='Vin_Number',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='WashInTimings',
            new_name='Wash_In_Timings',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='WashOutTimings',
            new_name='Wash_Out_Timings',
        ),
    ]
