# Generated by Django 5.0 on 2023-12-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicleDetails", "0005_alter_vehicledetail_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledetail",
            name="Date",
            field=models.DateField(),
        ),
    ]
