# Generated by Django 4.2.8 on 2023-12-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0005_rename_contactnumber_vehicledetail_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleDetail',
            new_name='Vehicle_Detail',
        ),
    ]
