# Generated by Django 4.2.8 on 2023-12-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0006_rename_vehicledetail_vehicle_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle_Detail',
            new_name='VehicleDetail',
        ),
    ]
