# Generated by Django 4.2.8 on 2023-12-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleDetails', '0007_rename_vehicle_detail_vehicledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='Contact_Number',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
